blank_issues_enabled: true
contact_links:
  - name: Questions & Help
    url: https://github.com/hyochan/react-native-iap/discussions
    about: For general questions, help, and discussions, please use GitHub Discussions instead of creating an issue.
