name: CI - Android Build
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-android.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'android/**'
      - 'nitrogen/**'
      - 'example/android/**'
      - 'example/src/**'
      - 'package.json'
      - 'bun.lock'
      - 'nitro.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-android.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'android/**'
      - 'nitrogen/**'
      - 'example/android/**'
      - 'example/src/**'
      - 'package.json'
      - 'bun.lock'
      - 'nitro.json'
  merge_group:
    types:
      - checks_requested

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate nitrogen code
        run: bun run nitrogen

      - name: Install JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install example dependencies
        run: |
          cd example
          bun install
          # Remove circular references to prevent infinite recursion
          rm -rf node_modules/react-native-iap/example
          rm -rf node_modules/react-native-iap/node_modules

      - name: Build example for Android
        env:
          JAVA_OPTS: '-XX:MaxHeapSize=6g'
        run: |
          cd example/android
          ./gradlew build