name: CI / Example iOS

on:
  push:
    branches: [main, next]
    paths:
      - 'src/**'
      - 'ios/**'
      - 'IapExample/ios/**'
      - .github/workflows/ci-example-ios.yml

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'ios/**'
      - 'IapExample/ios/**'
      - .github/workflows/ci-example-ios.yml

jobs:
  build_ios_example:
    runs-on: macos-15
    env:
      NO_FLIPPER: 1
      IOS_SIMULATOR: 'platform=iOS Simulator,name=iPhone 16'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install dependencies for `IapExample/`
        run: yarn install --immutable
        working-directory: IapExample

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '16.3'

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@1db83fb06b0da378aa7db7a1110923b904417cbc # v2.1.0
        continue-on-error: true
        with:
          cache_key: ${{ runner.os }}-buildcache-${{ hashFiles('**/Podfile.lock') }}-${{ hashFiles('**/Podfile')}}

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@eaecf785f6a34567a6d97f686bbb7bccc1ac1e5c # v1.237.0
        with:
          working-directory: IapExample
          bundler-cache: true
          ruby-version: '3.2'

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint
        run: yarn lint:swift

      - name: Verify no files have changed after auto-fix
        run: git diff --exit-code HEAD '*.swift'

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: |
            IapExample/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock')}}-${{ hashFiles('**/Podfile')}}
          restore-keys: ${{ runner.os }}-pods-

      - name: Install Pods
        run: bundle exec pod install
        working-directory: IapExample/ios

      - name: Install xcpretty
        run: gem install xcpretty
        working-directory: IapExample/ios

      - name: Build App
        uses: sersoft-gmbh/xcodebuild-action@0ca4718a95614a09f11d8a588970a1ccc4c77619 # v3.2.0
        with:
          workspace: IapExample/ios/IapExample.xcworkspace
          scheme: IapExample
          sdk: iphonesimulator
          destination: ${{ env.IOS_SIMULATOR }}
          action: build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
