name: CI - Lint
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-lint.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'eslint.config.mjs'
      - '.eslintrc*'
      - 'prettier.config.*'
      - 'tsconfig.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-lint.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'eslint.config.mjs'
      - '.eslintrc*'
      - 'prettier.config.*'
      - 'tsconfig.json'
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup


      - name: Lint files
        run: node .yarn/releases/yarn-3.6.1.cjs lint

      - name: Typecheck files
        run: node .yarn/releases/yarn-3.6.1.cjs typecheck:lib
