name: CI - Library Build
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-library.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'nitrogen/**'
      - 'package.json'
      - 'bun.lock'
      - 'nitro.json'
      - 'react-native-builder-bob.config.js'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-library.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'nitrogen/**'
      - 'package.json'
      - 'bun.lock'
      - 'nitro.json'
      - 'react-native-builder-bob.config.js'
  merge_group:
    types:
      - checks_requested

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: bun run prepare
