name: CI - Library Build
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-library.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - 'nitro.json'
      - 'tsconfig.build.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-library.yml'
      - '.github/actions/**'
      - 'src/**'
      - 'package.json'
      - 'yarn.lock'
      - 'nitro.json'
      - 'tsconfig.build.json'
  merge_group:
    types:
      - checks_requested

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Ensure generated types are up to date
        run: |
          yarn generate:types
          git diff --exit-code -- src/types.ts

      - name: Build package
        run: node .yarn/releases/yarn-3.6.1.cjs prepare
