name: CI - Test
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-test.yml'
      - '.github/actions/**'
      - 'src/**/__tests__/**'
      - 'src/**/*.test.*'
      - 'jest.config.*'
      - 'jest.setup.*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-test.yml'
      - '.github/actions/**'
      - 'src/**/__tests__/**'
      - 'src/**/*.test.*'
      - 'jest.config.*'
      - 'jest.setup.*'
  merge_group:
    types:
      - checks_requested

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: bun run test --maxWorkers=2 --coverage
